# Generated by Django 3.0.4 on 2020-03-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('published_date', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['published_date'],
            },
        ),
    ]
