# Generated by Django 3.0.4 on 2020-03-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='source',
            field=models.CharField(default='default_value', max_length=250),
        ),
    ]
