# Generated by Django 3.0.4 on 2020-03-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_headline_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
